package com.ip.founder.apiplatform.pojo;

import com.ip.founder.apiplatform.dao.DataEntity;

import java.util.Date;

public class PlantFactory extends DataEntity<PlantFactory> {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.url
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.username
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.password
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.prison
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String prison;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.in_time
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_factory.in_time
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private Date inTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.id
	 * @return  the value of plant_factory.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.id
	 * @param id  the value for plant_factory.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.name
	 * @return  the value of plant_factory.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.name
	 * @param name  the value for plant_factory.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.url
	 * @return  the value of plant_factory.url
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.url
	 * @param url  the value for plant_factory.url
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.username
	 * @return  the value of plant_factory.username
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.username
	 * @param username  the value for plant_factory.username
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.password
	 * @return  the value of plant_factory.password
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.password
	 * @param password  the value for plant_factory.password
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.prison
	 * @return  the value of plant_factory.prison
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPrison() {
		return prison;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.prison
	 * @param prison  the value for plant_factory.prison
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPrison(String prison) {
		this.prison = prison;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.type
	 * @return  the value of plant_factory.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.type
	 * @param type  the value for plant_factory.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}
	
	public String getPort() {
		return port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_factory.in_time
	 * @return  the value of plant_factory.in_time
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public Date getInTime() {
		return inTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_factory.in_time
	 * @param inTime  the value for plant_factory.in_time
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}
}