package com.ip.founder.apiplatform.pojo;

import com.ip.founder.apiplatform.dao.DataEntity;

public class PlantPerimeterRegion extends DataEntity<PlantPerimeterRegion> {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
//	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.remarks
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.parent_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String parent_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.code
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.region_level
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String regionLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_perimeter_region.source
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private Integer source;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_perimeter_region.id
	 * @return  the value of plant_perimeter_region.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
//	public String getId() {
//		return id;
//	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_perimeter_region.id
	 * @param id  the value for plant_perimeter_region.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
//	public void setId(String id) {
//		this.id = id;
//	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_perimeter_region.name
	 * @return  the value of plant_perimeter_region.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_perimeter_region.name
	 * @param name  the value for plant_perimeter_region.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_perimeter_region.remarks
	 * @return  the value of plant_perimeter_region.remarks
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_perimeter_region.remarks
	 * @param remarks  the value for plant_perimeter_region.remarks
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getParent_id() {
		return parent_id;
	}

	public void setParent_id(String parent_id) {
		this.parent_id = parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_perimeter_region.code
	 * @return  the value of plant_perimeter_region.code
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_perimeter_region.code
	 * @param code  the value for plant_perimeter_region.code
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_perimeter_region.region_level
	 * @return  the value of plant_perimeter_region.region_level
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getRegionLevel() {
		return regionLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_perimeter_region.region_level
	 * @param regionLevel  the value for plant_perimeter_region.region_level
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setRegionLevel(String regionLevel) {
		this.regionLevel = regionLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_perimeter_region.source
	 * @return  the value of plant_perimeter_region.source
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public Integer getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_perimeter_region.source
	 * @param source  the value for plant_perimeter_region.source
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setSource(Integer source) {
		this.source = source;
	}
}